### ISSUE TITLE
Add an option to allow one to opt-out of adding empty import lists

### ISSUE THREAD

**Issue by ThomasLamprecht** [perl-ide/App-perlimports#118]
While it might be OK by default to add empty import `()` statement to use statements that do not already import something so that they are future proofed against new default-exports it still adds a lot of noise and in bigger code bases that are under control by the same org it doesn't gains much value.

That's why I'd like to request a new option to opt-out of adding such "empty import statements" (or however they are called).

E.g., as of now the following line:

```perl
use Foo::Bar;
```

Always becomes

```perl
use Foo::Bar ();
```

With the newly proposed option that line should stay the same, at least if `Foo::Bar` is used at all.

Thanks for your consideration and for this module in general!

**Comment by oalders** [comment]
Thanks for this! My proposal would be to try to do this with the existing functionality. A few options:

```perl
use Foo::Bar; ## no perlimports
```

```shell
perlimports --ignore-module Foo::Bar ...
```

```shell
perlimports --create-config-file perlimports.toml
```

The config file gives you various options for default ignores:

```toml
ignore_modules                  = []
ignore_modules_filename         = ""
ignore_modules_pattern          = "" # regex like "^(Foo|Foo::Bar)"
ignore_modules_pattern_filename = ""
```

See https://metacpan.org/dist/App-perlimports/view/script/perlimports#-ignore-modules for a summary of these. The `*_filename` options are probably not so useful if you're already using a config file, but they are available. The would be more useful as command line switches, I think.
